### PR TITLE
Prefix predefined locals & add -literal

### LINKED ISSUE #24: Literals
Currently there isn't any way to output a literal `{{` or `}}` without changing the delimiter rock-wide.

How about if `{{ {{ }} something {{ }} }}` outputs `{{ something }}`? This would be fairly simple, just predefine values for the `{{` and `}}` tokens.

**Edit: you can output `}}`, but not `{{`.**

This would be a breaking change.

While we're at it, how about limiting valid tokens to `/[a-zA-Z0-9\-_]*/` (letters, numbers, `-`, and `_`)? That way future functionality could be added without breaking changes.

### PR DESCRIPTION
**Pull request by RyanZim**
Fixes #24. @jprichardson Look good?

### CODE REVIEW

**Comment by jprichardson** [comment]
I'm not crazy keen on it, but I value momentum and speed over minutiae. I think our answers will emerge as the software organically grows and gets used. So... looks good to me!

**Comment by RyanZim** [comment]
Now, time for me to write some docs!

**Comment by RyanZim** [comment]
> I'm not crazy keen on it

@jprichardson Sorry so long here; would you mind elaborating on that statement?

**Comment by jprichardson** [comment]
> @jprichardson Sorry so long here; 

It's alright, this is OSS - no obligations here :)

> would you mind elaborating on that statement?

I'm not a fan of the syntax. But I think that's okay. I value making decisions and moving over my nitpickiness :) That's why I don't care what decisions you pick, as it means we're moving forward and learning.

**Comment by RyanZim** [comment]
If you would prefer, we could keep the old syntax for backwards-compatibility, at least for a few releases.

I haven't stopped OSS, just been a bit busy with https://github.com/RyanZim/awesome-npm-scripts.

**Pull request merged**
