### PR TITLE
Normalize Code

### PR DESCRIPTION
**Pull request by RyanZim**
- Remove Trailing Whitespace
- Ensure one newline at EOF.

### CODE REVIEW

**Comment by jprichardson** [comment]
Let's just use `standard`, sound good?

**Comment by RyanZim** [comment]
I had tried `standard` earlier, however, I'm not sure how to eliminate some errors. For example:
```
/home/ryan/rock/lib/rock.js:52:17: Expected error to be handled.
```
nextflow is handling errors here.

**Comment by jprichardson** [comment]
> nextflow is handling errors here.

Cool, let's kill the usage of nextflow.

**Comment by RyanZim** [comment]
> Cool, let's kill the usage of nextflow.

@jprichardson What do you have in mind?

**Comment by jprichardson** [comment]
> Use named functions and have each function call the next one? 

This sounds great.

**Comment by RyanZim** [comment]
Removed nextflow, now for standard...

**Comment by RyanZim** [comment]
@jprichardson All done! :tada:

**Comment by jprichardson** [comment]
Awesome, thank you!

**Pull request merged**
