### PR TITLE
Promisify rock

### PR DESCRIPTION
**Pull request by RyanZim**
This is a breaking change.

I removed batchflow in favor of `Promise.all`. Since we are using `graceful-fs`, there is no reason to limit concurrency.

Given the fact that I'm getting tired, I suppose I've made a few mistakes and used a few anti-patterns. I will review later. @jprichardson If you want to merge before I get to it, IDK; just check the changes _very carefully._

### CODE REVIEW

**Comment by RyanZim** [comment]
Looked over this, didn't see anything out of order. @jprichardson Can you review and merge? Thanks!

**Comment by RyanZim** [comment]
After this, I guess I'll ship the next release.

**Comment by jprichardson** [comment]
@RyanZim have you considered using Babel w/ async/await? I may have you asked this already and apologize in advance, but it effectively makes using promises either since async/wait is literally sugar on top of promises i.e. an `async` function returns a Promise (not sure if you may have already have known this).

**Comment by RyanZim** [comment]
@jprichardson Yeah, I'm not entirely closed to that idea, but I'm impatient for the next release, I want some of the features I've implemented; so this will definitely not be in `v0.4`.

Regarding whether I will do this later:

1. I'm hesitant to introduce a build step here. Every line of code I write for the front-end needs to be compiled in some way. I'm satisfied with that, but I've had my fair share of frustrations with file watchers, etc. Sometimes it's refreshing not to deal with that for node.js.
1. I'm always slow to adopt new things, so perhaps this is all quite unreasonable. Eg. I wrote plain css for years before I finally switched to postcss/cssnext. I even resisted JS promises for quite a while; I only started using them after node.js natively supported them. Looking back, it all seems quite silly, but...that's just my nature.
1. The promise syntax isn't _that_ ugly. `async/await` is a little cleaner, but I'm not sure if it's worth the effort.
1. I don't have time to port `rock` to ES-next ATM.

I will give this some thought... Maybe someday...

---

Is this PR merge-ready in your opinion?

**Pull request merged**
